Update start and install script to leverage docker-compose

diff --git a/install b/install
--- a/install
+++ b/install
@@ -21,24 +21,81 @@ done
 
 # create and activate venv
 # TODO This should be removed as soon as the service is fully executed through fig.
-[[ -d "${CALIOPEN_DIR}/venv" ]] || virtualenv ${VENV_OPTS} "${CALIOPEN_DIR}/venv"
-source "${CALIOPEN_DIR}/venv/bin/activate"
+command -v virtualenv >/dev/null 2>&1 && VIRTUALENV_CMD="virtualenv"
+[[ -n "${VIRTUALENV_CMD}" ]] || command -v virtualenv2 >/dev/null 2>&1 && VIRTUALENV_CMD="virtualenv2"
+command -v pip >/dev/null 2>&1 && PIP_CMD="pip"
+[[ -n "${PIP_CMD}" ]] || command -v pip2 >/dev/null 2>&1 && PIP_CMD="pip2"
+command -v python >/dev/null 2>&1 && PYTHON_CMD="python"
+[[ -n "${PYTHON_CMD}" ]] || command -v python2 >/dev/null 2>&1 && PYTHON_CMD="python2"
+
+if [[ -n "${VIRTUALENV_CMD}" ]]
+then
+    # setup and activate virtualenv
+    [[ -d "${CALIOPEN_DIR}/venv" ]] || $VIRTUALENV_CMD ${VENV_OPTS} "${CALIOPEN_DIR}/venv"
+    source "${CALIOPEN_DIR}/venv/bin/activate"
+else
+    # There is no virtualenv command.
+    # This is an install script for development purpose
+    # There shold be an isolation of some kind.
+    echo "This is an install script for development purpose, it is recommanded"
+    echo "you isolate the environment using virtualenv or docker."
+    echo "Docker installation is not ready yet, so virtualenv is recommanded."
+    echo ""
+    echo "virtualenv command not found, only remaining option is to install"
+    echo "globally."
+    echo ""
+    read -p "Install anyway? (y/N)" -n 1 -r
+    if [[ ! $REPLY =~ ^[Yy]$ ]]
+    then
+        exit 1
+    fi
+fi
+
+if [[ -z "$PYTHON_CMD" ]] || [[ -z "$PIP_CMD" ]]
+then
+    echo "pip and python are required to install locally."
+    echo "Exiting"
+        exit 1
+fi
+
+
 # setup all deps in venv
 for d in ${CALIOPEN_COMPONENTS}
 do
 
   cd "${CALIOPEN_DIR}/${d}"
   if [ -f setup.py ] ; then
-    python setup.py develop
+    $PYTHON_CMD setup.py develop
   fi
   if [ -e requirements.txt ] ; then
-    pip install -r requirements.txt
+    $PIP_CMD install -r requirements.txt
   fi
 
 done
 
-# Install fig in virtualenv
-[[ -z "$(which fig)" ]] && pip install fig
+# install node dependencies using docker container
+command -v docker-compose >/dev/null 2>&1 && COMPOSE_CMD="docker-compose"
+[[ -z "${COMPOSE_CMD}" ]] && command -v fig >/dev/null 2>&1 && COMPOSE_CMD="fig"
+[[ -z "${COMPOSE_CMD}" ]] || COMPOSE_CMD="${COMPOSE_CMD} -f ${DEV_DIR}/fig.yml"
+
+if [[ -n "${COMPOSE_CMD}" ]]; then
+    function node {
+        $COMPOSE_CMD run node $@
+    }
+    function npm {
+        $COMPOSE_CMD run npm $@
+    }
+    function ember {
+        $COMPOSE_CMD run ember $@
+    }
+    function bower {
+        $COMPOSE_CMD run node ./node_modules/.bin/bower $@
+    }
+
+elif ! command -v npm >/dev/null 2>&1 ; then
+    echo "docker-compose, fig or npm are required to install mimosa"
+    exit 1
+fi
 
 
 # Create fig data folders
@@ -49,20 +106,6 @@ cd "${CALIOPEN_DIR}"
 # Install frontend
 # ================
 cd "${CALIOPEN_DIR}/frontend"
-# Use fig to launch npm if no local npm is found
-command -v npm >/dev/null 2>&1 || supercharge_npm=1
-if [[ ! -z "$supercharge_npm" ]]
-then
-    function node {
-        fig -f ${DEV_DIR}/fig.yml run node $@
-    }
-    function npm {
-        fig -f ${DEV_DIR}/fig.yml run npm $@
-    }
-    function ember {
-        fig -f ${DEV_DIR}/fig.yml run ember $@
-    }
-fi
 source ./bin/install
 declare ret="$?"
 [[ "0" -eq "$ret" ]] || exit $ret
